import {
  Company,
  Round,
  Question,
  Offer,
  Task,
  EventItem,
  ResumeVersion,
  FollowUp,
  PlacementGoal,
  ActivityItem,
  HeatmapDay,
  UserProfile,
} from "@/types";

export const initialUserProfile: UserProfile = {
  name: "Alex Sharma",
  college: "National Institute of Technology",
  branch: "Computer Science & Engineering",
  targetCtc: "₹25+ LPA",
  graduationYear: "2027",
  seasonName: "2026-27 Final Placements",
};

export const sampleCompanies: Company[] = [
  {
    id: "comp-1",
    name: "Microsoft",
    role: "Software Engineer",
    jobType: "Full Time",
    location: "Hyderabad / Bangalore",
    category: "Product",
    source: "Campus",
    applicationDate: "2026-08-15",
    deadline: "2026-09-25",
    status: "Offer Received",
    currentRoundName: "Offer Finalized",
    nextRoundName: "Offer Acceptance",
    packageStipend: "₹45 LPA",
    expectedCtc: "₹40 LPA",
    offeredCtc: "₹45.2 LPA",
    recruiter: {
      name: "Pooja Hegde",
      role: "University Talent Acquisition Lead",
      email: "pooja.hegde@microsoft.com",
      linkedin: "https://linkedin.com/in/pooja-hegde-talent",
      phone: "+91 98765 43210",
      notes: "Very responsive. Sent official letter on Sept 10.",
    },
    applicationUrl: "https://careers.microsoft.com/students",
    resumeVersionId: "res-1",
    notes: "Cleared all 4 rounds. Team match: Azure Core Systems. Signing bonus included.",
    tags: ["Tier-1", "Dream", "PPO", "Distributed Systems"],
    createdAt: "2026-08-15T09:00:00Z",
    updatedAt: "2026-09-10T18:00:00Z",
    isSample: true,
  },
  {
    id: "comp-2",
    name: "Google",
    role: "Software Engineer",
    jobType: "Full Time",
    location: "Bangalore",
    category: "Product",
    source: "Campus",
    applicationDate: "2026-08-20",
    deadline: "2026-09-18",
    status: "Technical Round",
    currentRoundName: "Technical Round 2",
    nextRoundName: "Managerial / Googliness",
    packageStipend: "₹38 LPA",
    expectedCtc: "₹38 LPA",
    recruiter: {
      name: "Arjun Verma",
      role: "Staff Recruiter",
      email: "arjun.verma@google.com",
      linkedin: "https://linkedin.com/in/arjun-recruits",
    },
    applicationUrl: "https://google.com/careers",
    resumeVersionId: "res-1",
    notes: "Round 1 went really well on Graph Algorithms & Trie. Round 2 focused on concurrency and dynamic programming.",
    tags: ["Tier-1", "FAANG", "DSA Intensive"],
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-09-11T14:30:00Z",
    isSample: true,
  },
  {
    id: "comp-3",
    name: "NVIDIA",
    role: "ML Engineer",
    jobType: "Full Time",
    location: "Pune / Bangalore",
    category: "AI/ML",
    source: "Referral",
    applicationDate: "2026-08-25",
    deadline: "2026-09-14",
    status: "Technical Round",
    currentRoundName: "Technical Round 1",
    nextRoundName: "Deep Learning Systems Round",
    packageStipend: "₹34 LPA",
    expectedCtc: "₹30 LPA",
    recruiter: {
      name: "Siddharth Rao",
      role: "AI Tech Recruiter",
      email: "siddharth.r@nvidia.com",
    },
    applicationUrl: "https://nvidia.wd5.myworkdayjobs.com",
    resumeVersionId: "res-2",
    notes: "Cleared OA with 88%. Technical round scheduled on Sept 14 at 2:00 PM.",
    tags: ["AI/ML", "CUDA", "LLM Serving", "Dream"],
    createdAt: "2026-08-25T11:00:00Z",
    updatedAt: "2026-09-11T16:00:00Z",
    isSample: true,
  },
  {
    id: "comp-4",
    name: "Amazon",
    role: "Software Development Engineer (SDE-1)",
    jobType: "Full Time",
    location: "Hyderabad",
    category: "Product",
    source: "Campus",
    applicationDate: "2026-08-18",
    deadline: "2026-09-16",
    status: "Assessment",
    currentRoundName: "Online Assessment 2",
    nextRoundName: "Technical Loop (3 Rounds)",
    packageStipend: "₹35 LPA",
    expectedCtc: "₹32 LPA",
    recruiter: {
      name: "Meera Nair",
      email: "meeran@amazon.com",
    },
    applicationUrl: "https://amazon.jobs",
    resumeVersionId: "res-1",
    notes: "OA1 completed (Debugging + 2 DSA coding). OA2 work simulation pending due Sept 16.",
    tags: ["Leadership Principles", "Tier-1", "Product"],
    createdAt: "2026-08-18T14:00:00Z",
    updatedAt: "2026-09-09T10:00:00Z",
    isSample: true,
  },
  {
    id: "comp-5",
    name: "Uber",
    role: "Backend Developer",
    jobType: "Full Time",
    location: "Bangalore",
    category: "Product",
    source: "LinkedIn",
    applicationDate: "2026-08-28",
    deadline: "2026-09-19",
    status: "Shortlisted",
    currentRoundName: "CodeSignal Assessment",
    nextRoundName: "Architecture Screening",
    packageStipend: "₹42 LPA",
    expectedCtc: "₹38 LPA",
    recruiter: {
      name: "Rohan Kapoor",
      email: "rkapoor@uber.com",
    },
    applicationUrl: "https://uber.com/careers",
    resumeVersionId: "res-1",
    notes: "Resume shortlisted through recruiter reach-out on LinkedIn. CodeSignal test link expected this Friday.",
    tags: ["High Scale", "FinTech/Mobility"],
    createdAt: "2026-08-28T09:30:00Z",
    updatedAt: "2026-09-08T11:00:00Z",
    isSample: true,
  },
  {
    id: "comp-6",
    name: "Atlassian",
    role: "Full Stack Developer",
    jobType: "Full Time",
    location: "Bengaluru (Remote First)",
    category: "SaaS",
    source: "Campus",
    applicationDate: "2026-08-10",
    deadline: "2026-09-05",
    status: "Rejected",
    currentRoundName: "Technical Round 2 (System Design)",
    rejectionStage: "Technical Round 2",
    rejectionReason: "Fumbled on distributed cache invalidation strategies and WebSocket scalability during live architecture design.",
    packageStipend: "₹52 LPA",
    expectedCtc: "₹45 LPA",
    resumeVersionId: "res-1",
    notes: "Gave strong coding performance in Round 1, but needed more depth in real-time microservices design for Round 2.",
    tags: ["Remote", "SaaS", "Top CTC"],
    createdAt: "2026-08-10T12:00:00Z",
    updatedAt: "2026-09-06T15:00:00Z",
    isSample: true,
  },
  {
    id: "comp-7",
    name: "Goldman Sachs",
    role: "Quantitative Technology Analyst",
    jobType: "Full Time",
    location: "Bengaluru",
    category: "FinTech",
    source: "Campus",
    applicationDate: "2026-08-12",
    deadline: "2026-09-02",
    status: "Rejected",
    currentRoundName: "Online Assessment (Math + Coding)",
    rejectionStage: "Online Assessment",
    rejectionReason: "Aptitude and probability cutoff was extremely high (estimated 92%+). Missed by 2 questions in combinatorics.",
    packageStipend: "₹30 LPA",
    expectedCtc: "₹28 LPA",
    resumeVersionId: "res-3",
    notes: "OA had 2 Hard DSA + 10 Probability questions. Need to practice Markov chains & Bayes theorem.",
    tags: ["FinTech", "Quant", "Math Heavy"],
    createdAt: "2026-08-12T10:00:00Z",
    updatedAt: "2026-09-03T16:00:00Z",
    isSample: true,
  },
  {
    id: "comp-8",
    name: "CRED",
    role: "Backend Engineer",
    jobType: "Full Time",
    location: "Bengaluru",
    category: "FinTech",
    source: "Hackathon",
    applicationDate: "2026-08-30",
    deadline: "2026-09-20",
    status: "Managerial Round",
    currentRoundName: "Engineering Culture & Tech Deepdive",
    nextRoundName: "Founder's Round",
    packageStipend: "₹36 LPA",
    expectedCtc: "₹35 LPA",
    recruiter: {
      name: "Tanya Sen",
      email: "tanya.sen@cred.club",
      phone: "+91 99887 76655",
    },
    applicationUrl: "https://cred.club/careers",
    resumeVersionId: "res-1",
    notes: "Shortlisted directly to Round 2 after winning Top 5 in CRED HackFest.",
    tags: ["Startup", "FinTech", "Fast Paced"],
    createdAt: "2026-08-30T15:00:00Z",
    updatedAt: "2026-09-11T12:00:00Z",
    isSample: true,
  },
  {
    id: "comp-9",
    name: "TCS",
    role: "Digital Systems Engineer",
    jobType: "Full Time",
    location: "Mumbai / Pan India",
    category: "Service",
    source: "Campus",
    applicationDate: "2026-08-01",
    deadline: "2026-08-25",
    status: "Offer Accepted",
    currentRoundName: "HR & Document Verification",
    packageStipend: "₹9.5 LPA",
    expectedCtc: "₹9.0 LPA",
    offeredCtc: "₹9.5 LPA",
    recruiter: {
      name: "Rajesh Kulkarni",
      email: "rajesh.k@tcs.com",
    },
    resumeVersionId: "res-1",
    notes: "Backup safety offer secured on Campus day 1.",
    tags: ["Campus", "Safety", "Offer In Hand"],
    createdAt: "2026-08-01T08:00:00Z",
    updatedAt: "2026-08-26T17:00:00Z",
    isSample: true,
  },
  {
    id: "comp-10",
    name: "Adobe",
    role: "Member of Technical Staff",
    jobType: "Full Time",
    location: "Noida / Bangalore",
    category: "Product",
    source: "Campus",
    applicationDate: "2026-09-01",
    deadline: "2026-09-15",
    status: "Applied",
    currentRoundName: "Application Shortlist",
    nextRoundName: "Online Coding Test",
    packageStipend: "₹40 LPA",
    expectedCtc: "₹36 LPA",
    applicationUrl: "https://adobe.wd5.myworkdayjobs.com",
    resumeVersionId: "res-1",
    notes: "Applied via Campus Placement Cell portal. OA expected Sept 15.",
    tags: ["Tier-1", "Creative Cloud"],
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
    isSample: true,
  },
  {
    id: "comp-11",
    name: "Oracle",
    role: "Cloud Systems Engineer",
    jobType: "Full Time",
    location: "Hyderabad",
    category: "Cloud",
    source: "Campus",
    applicationDate: "2026-08-14",
    deadline: "2026-08-30",
    status: "Rejected",
    currentRoundName: "Technical Round 1",
    rejectionStage: "Technical Round 1",
    rejectionReason: "Struggled with SQL indexing internals (B-Tree vs Hash index) and OS memory paging questions.",
    packageStipend: "₹20 LPA",
    expectedCtc: "₹18 LPA",
    resumeVersionId: "res-1",
    notes: "Need stronger revision on OS & DBMS storage engines.",
    tags: ["Cloud", "Database"],
    createdAt: "2026-08-14T09:00:00Z",
    updatedAt: "2026-08-31T11:00:00Z",
    isSample: true,
  },
  {
    id: "comp-12",
    name: "Flipkart",
    role: "SDE-1",
    jobType: "Full Time",
    location: "Bengaluru",
    category: "E-Commerce",
    source: "Campus",
    applicationDate: "2026-08-16",
    deadline: "2026-08-28",
    status: "Rejected",
    rejectionStage: "Resume",
    rejectionReason: "Resume screening cutoff was strictly top 15% CGPA or Competitive Programming rating 1800+.",
    packageStipend: "₹32 LPA",
    expectedCtc: "₹30 LPA",
    resumeVersionId: "res-1",
    notes: "Applied with Resume v1. Should tailor future resumes for e-commerce scale highlights.",
    tags: ["E-Commerce", "High Volume"],
    createdAt: "2026-08-16T11:00:00Z",
    updatedAt: "2026-08-29T10:00:00Z",
    isSample: true,
  },
];

export const sampleRounds: Round[] = [
  // Microsoft Rounds
  {
    id: "rnd-ms-1",
    companyId: "comp-1",
    name: "Application & Resume Shortlist",
    type: "Application",
    order: 1,
    date: "2026-08-15",
    status: "Cleared",
    score: "100%",
    durationMinutes: 15,
    feedback: "Strong resume with solid open source and systems projects.",
    notes: "Passed automatic ATS and department screening.",
  },
  {
    id: "rnd-ms-2",
    companyId: "comp-1",
    name: "Online Assessment (OA)",
    type: "Online Assessment",
    order: 2,
    date: "2026-08-22",
    status: "Cleared",
    score: "92%",
    durationMinutes: 90,
    feedback: "Solved 3 out of 3 problems within 55 minutes with 100% test cases passing.",
    performanceRating: 5,
    checklist: [
      { id: "c1", label: "Trees & Binary Search Trees", completed: true },
      { id: "c2", label: "Dynamic Programming Strings", completed: true },
      { id: "c3", label: "Graph BFS/DFS", completed: true },
    ],
  },
  {
    id: "rnd-ms-3",
    companyId: "comp-1",
    name: "Technical Round 1",
    type: "Technical Round 1",
    order: 3,
    date: "2026-08-28",
    status: "Cleared",
    score: "4.8 / 5",
    durationMinutes: 60,
    interviewer: "Venkatesh S (Principal SDE)",
    topicsAsked: ["LRU Cache Implementation", "Trie Prefix Search", "OS Deadlocks"],
    feedback: "Excellent clarity in explaining edge cases and memory layouts in C++.",
    performanceRating: 5,
    checklist: [
      { id: "c4", label: "LRU Cache custom doubly linked list", completed: true },
      { id: "c5", label: "Multi-threading synchronization lock", completed: true },
    ],
  },
  {
    id: "rnd-ms-4",
    companyId: "comp-1",
    name: "Technical Round 2",
    type: "Technical Round 2",
    order: 4,
    date: "2026-09-04",
    status: "Cleared",
    score: "4.7 / 5",
    durationMinutes: 60,
    interviewer: "Ananya Roy (Senior Engineering Manager)",
    topicsAsked: ["Rate Limiter System Design", "Subarray Sum Equals K", "DBMS Sharding"],
    feedback: "Great approach to Token Bucket vs Leaky Bucket algorithms for rate limiting.",
    performanceRating: 5,
  },
  {
    id: "rnd-ms-5",
    companyId: "comp-1",
    name: "Managerial & HR Round",
    type: "HR Round",
    order: 5,
    date: "2026-09-08",
    status: "Cleared",
    score: "Selected",
    durationMinutes: 45,
    interviewer: "Deepak Sharma (Director of Engineering)",
    topicsAsked: ["Conflict resolution in team projects", "Why Microsoft?", "Growth mindset"],
    feedback: "High cultural alignment and proactive ownership mindset.",
    performanceRating: 5,
  },

  // Google Rounds
  {
    id: "rnd-goog-1",
    companyId: "comp-2",
    name: "Resume Shortlisting",
    type: "Application",
    order: 1,
    date: "2026-08-20",
    status: "Cleared",
    score: "Cleared",
  },
  {
    id: "rnd-goog-2",
    companyId: "comp-2",
    name: "Technical Screening OA",
    type: "Online Assessment",
    order: 2,
    date: "2026-08-29",
    status: "Cleared",
    score: "85%",
    durationMinutes: 90,
    feedback: "Cleared Google Online Challenge with 2 DSA solved.",
  },
  {
    id: "rnd-goog-3",
    companyId: "comp-2",
    name: "Technical Round 1 (Data Structures)",
    type: "Technical Round 1",
    order: 3,
    date: "2026-09-07",
    status: "Cleared",
    score: "Strong Hire",
    durationMinutes: 45,
    interviewer: "Kiran G (L5 SDE)",
    topicsAsked: ["Shortest Path in Weighted DAG with Obstacles", "Custom Min-Max Heap"],
    feedback: "Demonstrated optimal asymptotic time and space complexity with clean modular code.",
    performanceRating: 5,
  },
  {
    id: "rnd-goog-4",
    companyId: "comp-2",
    name: "Technical Round 2 (Algorithms & Systems)",
    type: "Technical Round 2",
    order: 4,
    date: "2026-09-15",
    time: "11:00 AM",
    status: "Scheduled",
    durationMinutes: 45,
    interviewer: "Aditi Mathur (Staff SDE)",
    checklist: [
      { id: "g1", label: "Dynamic Programming on Trees", completed: true },
      { id: "g2", label: "Segment Trees & Fenwick Trees", completed: false },
      { id: "g3", label: "Concurrency & Mutex primitives", completed: true },
      { id: "g4", label: "Project deep-dive explanations", completed: true },
    ],
    notes: "Scheduled for Sept 15, 11:00 AM via Google Meet. Revise Segment Trees!",
  },

  // NVIDIA Rounds
  {
    id: "rnd-nv-1",
    companyId: "comp-3",
    name: "Resume & Portfolio Review",
    type: "Application",
    order: 1,
    date: "2026-08-25",
    status: "Cleared",
    score: "100%",
  },
  {
    id: "rnd-nv-2",
    companyId: "comp-3",
    name: "AI/ML Coding Assessment",
    type: "Online Assessment",
    order: 2,
    date: "2026-09-02",
    status: "Cleared",
    score: "88%",
    durationMinutes: 90,
    topicsAsked: ["PyTorch Custom Autograd", "Matrix Multiplication optimization", "Vector Search"],
  },
  {
    id: "rnd-nv-3",
    companyId: "comp-3",
    name: "Technical Round 1 (Deep Learning)",
    type: "Technical Round 1",
    order: 3,
    date: "2026-09-14",
    time: "02:00 PM",
    status: "Scheduled",
    durationMinutes: 60,
    checklist: [
      { id: "nv1", label: "Transformer Attention Architecture", completed: true },
      { id: "nv2", label: "FlashAttention & KV Cache internals", completed: false },
      { id: "nv3", label: "Quantization (FP8, INT4, AWQ)", completed: true },
      { id: "nv4", label: "GPU Memory profiling", completed: false },
    ],
    notes: "Focus heavily on LLM inference latency bottlenecks.",
  },
];

export const sampleQuestions: Question[] = [
  {
    id: "q-1",
    companyId: "comp-1",
    companyName: "Microsoft",
    roundId: "rnd-ms-3",
    roundName: "Technical Round 1",
    question: "Design and implement an LRU Cache with O(1) get and put operations.",
    category: "DSA",
    difficulty: "Medium",
    myAnswer:
      "Used a HashMap + Doubly Linked List. Map stores key -> Node pointers. Most recently accessed nodes are moved to head; least recently used nodes at tail get evicted when capacity is reached.",
    correctAnswer:
      "HashMap mapping key to node references in a Doubly Linked List. When get(key) is invoked, move node to head. When put(key, value) exceeds capacity, pop tail.prev and erase from map.",
    confidence: 5,
    needsRevision: false,
    dateAdded: "2026-08-28",
    tags: ["Data Structures", "Linked List", "Hashing"],
  },
  {
    id: "q-2",
    companyId: "comp-1",
    companyName: "Microsoft",
    roundId: "rnd-ms-4",
    roundName: "Technical Round 2",
    question: "What is Database Normalization and explain 1NF, 2NF, 3NF, and BCNF with examples?",
    category: "DBMS",
    difficulty: "Medium",
    myAnswer:
      "Normalization eliminates data redundancy and prevents insertion, deletion, and update anomalies through functional dependencies.",
    correctAnswer:
      "1NF: Atomic values; 2NF: 1NF + No partial dependency on candidate keys; 3NF: 2NF + No transitive dependencies; BCNF: For every X -> Y, X must be a superkey.",
    confidence: 4,
    needsRevision: false,
    dateAdded: "2026-09-04",
    tags: ["DBMS", "Theory", "Normalization"],
  },
  {
    id: "q-3",
    companyId: "comp-11",
    companyName: "Oracle",
    roundId: "rnd-ora-1",
    roundName: "Technical Round 1",
    question: "Explain database normalization and difference between 3NF and BCNF.",
    category: "DBMS",
    difficulty: "Medium",
    myAnswer: "Explained 1NF, 2NF, 3NF but missed edge case in overlapping candidate keys for BCNF.",
    confidence: 3,
    needsRevision: true,
    dateAdded: "2026-08-31",
    tags: ["DBMS", "Theory", "Normalization"],
  },
  {
    id: "q-4",
    companyId: "comp-2",
    companyName: "Google",
    roundId: "rnd-goog-3",
    roundName: "Technical Round 1",
    question: "Given a directed acyclic graph with obstacles, find the shortest path cost with k modifications allowed.",
    category: "DSA",
    difficulty: "Hard",
    myAnswer:
      "Dijkstra algorithm extended with state (node, k_remaining) as the distance matrix dist[node][k].",
    correctAnswer:
      "Modified Dijkstra / 0-1 BFS state space search tracking min distance to (node, k). Complexity O((V*k + E*k) log(V*k)).",
    confidence: 5,
    needsRevision: false,
    dateAdded: "2026-09-07",
    tags: ["Graph", "Dijkstra", "Shortest Path"],
  },
  {
    id: "q-5",
    companyId: "comp-3",
    companyName: "NVIDIA",
    roundId: "rnd-nv-2",
    roundName: "Online Assessment",
    question: "How does KV Caching reduce autoregressive LLM decoding latency and memory complexity?",
    category: "AI",
    difficulty: "Hard",
    myAnswer:
      "It caches Key and Value matrices for past tokens so subsequent tokens don't recompute self-attention over the whole sequence.",
    correctAnswer:
      "Without KV cache, generation is O(N^2) in computation per step. With KV cache, only current query vector Q_t is computed against cached K_1..t and V_1..t, reducing compute to O(N) per step at the cost of O(B * L * H * D) memory.",
    confidence: 4,
    needsRevision: true,
    dateAdded: "2026-09-02",
    tags: ["Transformer", "LLM", "Inference"],
  },
  {
    id: "q-6",
    companyId: "comp-6",
    companyName: "Atlassian",
    roundName: "Technical Round 2",
    question: "Design a scalable Distributed Rate Limiter with multi-region consistency.",
    category: "System Design",
    difficulty: "Hard",
    myAnswer: "Suggested Redis with Token Bucket and TTL sync.",
    correctAnswer:
      "Sliding Window Counter using Redis sorted sets or Lua script with atomic increments. Use local memory cache with async batch sync to central Redis cluster to reduce latency spikes.",
    confidence: 3,
    needsRevision: true,
    dateAdded: "2026-09-05",
    tags: ["System Design", "Rate Limiter", "Redis"],
  },
  {
    id: "q-7",
    companyId: "comp-1",
    companyName: "Microsoft",
    roundName: "Technical Round 2",
    question: "How to design a Distributed Rate Limiter using Token Bucket algorithm?",
    category: "System Design",
    difficulty: "Medium",
    myAnswer:
      "Used Redis hash storing last_refill_timestamp and current_tokens with atomic Lua script execution.",
    confidence: 5,
    needsRevision: false,
    dateAdded: "2026-09-04",
    tags: ["System Design", "Rate Limiter"],
  },
];

export const sampleOffers: Offer[] = [
  {
    id: "off-1",
    companyId: "comp-1",
    companyName: "Microsoft",
    role: "Software Engineer",
    baseSalary: "₹22 LPA",
    totalCtc: "₹45.2 LPA",
    joiningBonus: "₹6 LPA",
    stocks: "$35,000 (~₹29 LPA over 4 years)",
    location: "Hyderabad / Bangalore",
    bond: "None",
    workMode: "Hybrid",
    offerDate: "2026-09-10",
    joiningDate: "2027-07-15",
    deadlineDate: "2026-09-25",
    status: "Received",
    notes: "Relocation allowance ₹2,50,000 + comprehensive health insurance for family.",
    perks: [
      "₹22L Base Salary",
      "₹6L First Year Joining Bonus",
      "$35K Microsoft RSUs (25% vesting/yr)",
      "Hybrid (3 days in office, 2 days remote)",
      "₹2.5L Relocation Bonus",
    ],
  },
  {
    id: "off-2",
    companyId: "comp-9",
    companyName: "TCS",
    role: "Digital Systems Engineer",
    baseSalary: "₹9.0 LPA",
    totalCtc: "₹9.5 LPA",
    location: "Mumbai / Pune",
    bond: "1 Year (₹50,000)",
    workMode: "On-site",
    offerDate: "2026-08-26",
    joiningDate: "2027-08-01",
    deadlineDate: "2026-09-30",
    status: "Accepted",
    notes: "Safety benchmark offer accepted on Day 1 of campus placement.",
    perks: ["Health Insurance ₹5L", "Standard Corporate Benefits"],
  },
];

export const sampleTasks: Task[] = [
  {
    id: "tsk-1",
    title: "Revise Segment Trees & Fenwick Trees for Google Round 2",
    companyId: "comp-2",
    companyName: "Google",
    category: "DSA",
    priority: "Urgent",
    dueDate: "2026-09-13",
    completed: false,
    durationMinutes: 90,
    notes: "Focus on range update query and lazy propagation templates.",
  },
  {
    id: "tsk-2",
    title: "Prepare FlashAttention & KV-cache derivation for NVIDIA interview",
    companyId: "comp-3",
    companyName: "NVIDIA",
    category: "Project Prep",
    priority: "Urgent",
    dueDate: "2026-09-13",
    completed: false,
    durationMinutes: 120,
    notes: "Review memory bandwidth vs compute bound GPU roofline model.",
  },
  {
    id: "tsk-3",
    title: "Complete Amazon OA2 Work Style Assessment simulation",
    companyId: "comp-4",
    companyName: "Amazon",
    category: "Application",
    priority: "High",
    dueDate: "2026-09-14",
    completed: false,
    durationMinutes: 60,
    notes: "Review 16 Amazon Leadership Principles, especially Customer Obsession & Bias for Action.",
  },
  {
    id: "tsk-4",
    title: "Follow up with Uber recruiter regarding CodeSignal test slot",
    companyId: "comp-5",
    companyName: "Uber",
    category: "Follow-up",
    priority: "Medium",
    dueDate: "2026-09-14",
    completed: false,
    durationMinutes: 15,
  },
  {
    id: "tsk-5",
    title: "Solve 5 Hard Dynamic Programming problems on LeetCode",
    category: "DSA",
    priority: "Medium",
    dueDate: "2026-09-15",
    completed: true,
    durationMinutes: 150,
  },
  {
    id: "tsk-6",
    title: "Revise SQL Indexing internals (B-Trees vs LSM Trees)",
    category: "Revision",
    priority: "High",
    dueDate: "2026-09-16",
    completed: false,
    durationMinutes: 60,
  },
];

export const sampleEvents: EventItem[] = [
  {
    id: "evt-1",
    companyId: "comp-3",
    companyName: "NVIDIA",
    type: "Technical Interview",
    title: "NVIDIA Technical Round 1 (Deep Learning Systems)",
    date: "2026-09-14",
    time: "02:00 PM",
    locationOrUrl: "https://nvidia.zoom.us/j/987123456",
    status: "Upcoming",
    notes: "Interviewer: Senior DL Architect. Prepare GPU optimization topics.",
  },
  {
    id: "evt-2",
    companyId: "comp-2",
    companyName: "Google",
    type: "Technical Interview",
    title: "Google Technical Round 2 (Algorithms & Concurrency)",
    date: "2026-09-15",
    time: "11:00 AM",
    locationOrUrl: "https://meet.google.com/xyz-abcd-efg",
    status: "Upcoming",
    notes: "Google Meet link. Have Google Docs live editor ready.",
  },
  {
    id: "evt-3",
    companyId: "comp-4",
    companyName: "Amazon",
    type: "OA Deadline",
    title: "Amazon OA2 Assessment Deadline",
    date: "2026-09-16",
    time: "11:59 PM",
    locationOrUrl: "https://hirepro.in/amazon-oa2",
    status: "Upcoming",
    notes: "90-minute work simulation test.",
  },
  {
    id: "evt-4",
    companyId: "comp-1",
    companyName: "Microsoft",
    type: "Offer Deadline",
    title: "Microsoft Offer Acceptance Deadline",
    date: "2026-09-25",
    time: "05:00 PM",
    status: "Upcoming",
    notes: "Sign offer letter PDF and upload via student portal.",
  },
  {
    id: "evt-5",
    companyId: "comp-8",
    companyName: "CRED",
    type: "Managerial Interview",
    title: "CRED Engineering Culture & Systems Round",
    date: "2026-09-18",
    time: "04:30 PM",
    locationOrUrl: "https://meet.google.com/cred-culture",
    status: "Upcoming",
    notes: "Discussion on past projects and product architectural challenges.",
  },
];

export const sampleResumeVersions: ResumeVersion[] = [
  {
    id: "res-1",
    name: "Resume v1 — SDE / Distributed Systems",
    targetRole: "Software Engineer / SDE-1",
    description: "Emphasizes C++, Go, Distributed Key-Value Store project, OS kernels, and LeetCode Knight badge (2050 rating).",
    fileUrl: "https://drive.google.com/file/d/sde_resume_v1",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-15T12:00:00Z",
  },
  {
    id: "res-2",
    name: "Resume v2 — AI/ML & LLM Systems",
    targetRole: "ML Engineer / AI Researcher",
    description: "Highlights PyTorch, CUDA custom kernels, FlashAttention implementation, and published research paper at NeurIPS workshop.",
    fileUrl: "https://drive.google.com/file/d/aiml_resume_v2",
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-08-24T14:00:00Z",
  },
  {
    id: "res-3",
    name: "Resume v3 — Quantitative & Data Analytics",
    targetRole: "Quant Analyst / Data Scientist",
    description: "Focuses on Stochastic Calculus, Econometrics, High Frequency Backtester in C++, and SQL/Pandas pipelines.",
    fileUrl: "https://drive.google.com/file/d/quant_resume_v3",
    createdAt: "2026-08-10T09:00:00Z",
    updatedAt: "2026-08-12T16:00:00Z",
  },
];

export const sampleFollowUps: FollowUp[] = [
  {
    id: "fol-1",
    companyId: "comp-5",
    companyName: "Uber",
    contactPerson: "Rohan Kapoor (Talent Acquisition)",
    contactMethod: "LinkedIn",
    message: "Hi Rohan, following up on our chat last week regarding the CodeSignal technical assessment slot.",
    status: "Pending",
    dueDate: "2026-09-14",
    notes: "Send polite reminder on Monday morning.",
  },
  {
    id: "fol-2",
    companyId: "comp-10",
    companyName: "Adobe",
    contactPerson: "Campus Placement Cell Coordinator",
    contactMethod: "Portal",
    message: "Inquiry on shortlisted student batch announcement date for Adobe OA.",
    status: "Contacted",
    dueDate: "2026-09-15",
    lastContactDate: "2026-09-10",
  },
];

export const sampleGoals: PlacementGoal[] = [
  {
    id: "g-1",
    title: "Apply to 25 Target Companies",
    category: "Applications",
    targetValue: 25,
    currentValue: 12,
    unit: "applications",
    completed: false,
  },
  {
    id: "g-2",
    title: "Clear 8 Online Assessments",
    category: "Interviews",
    targetValue: 8,
    currentValue: 6,
    unit: "assessments",
    completed: false,
  },
  {
    id: "g-3",
    title: "Solve 400 DSA Problems",
    category: "DSA",
    targetValue: 400,
    currentValue: 345,
    unit: "problems",
    completed: false,
  },
  {
    id: "g-4",
    title: "Secure a ₹30+ LPA Dream Offer",
    category: "Offers",
    targetValue: 1,
    currentValue: 1,
    unit: "offer",
    completed: true,
  },
  {
    id: "g-5",
    title: "Complete 15 Mock Technical Interviews",
    category: "Mocks",
    targetValue: 15,
    currentValue: 11,
    unit: "mocks",
    completed: false,
  },
];

export const sampleActivities: ActivityItem[] = [
  {
    id: "act-1",
    type: "offer_received",
    title: "Offer Received — Microsoft",
    description: "Received official selection letter for Software Engineer role (₹45.2 LPA CTC).",
    timestamp: "2026-09-10T17:45:00Z",
    companyId: "comp-1",
    companyName: "Microsoft",
  },
  {
    id: "act-2",
    type: "technical_cleared",
    title: "Cleared Technical Round 1 — Google",
    description: "Evaluated as 'Strong Hire' on Graph and Heap algorithms. Round 2 scheduled for Sept 15.",
    timestamp: "2026-09-08T14:30:00Z",
    companyId: "comp-2",
    companyName: "Google",
  },
  {
    id: "act-3",
    type: "technical_scheduled",
    title: "Technical Interview Scheduled — NVIDIA",
    description: "Technical Round 1 scheduled for Sept 14 at 2:00 PM.",
    timestamp: "2026-09-06T11:00:00Z",
    companyId: "comp-3",
    companyName: "NVIDIA",
  },
  {
    id: "act-4",
    type: "oa_cleared",
    title: "Cleared Online Assessment — Amazon",
    description: "Passed OA1 coding challenge with 100% test cases.",
    timestamp: "2026-09-04T16:00:00Z",
    companyId: "comp-4",
    companyName: "Amazon",
  },
  {
    id: "act-5",
    type: "shortlisted",
    title: "Resume Shortlisted — Uber",
    description: "Recruiter reached out on LinkedIn for Backend Developer profile.",
    timestamp: "2026-09-02T10:15:00Z",
    companyId: "comp-5",
    companyName: "Uber",
  },
  {
    id: "act-6",
    type: "applied",
    title: "Applied to Adobe",
    description: "Submitted application for Member of Technical Staff (MTS).",
    timestamp: "2026-09-01T09:00:00Z",
    companyId: "comp-10",
    companyName: "Adobe",
  },
];

// Generate 84 days (12 weeks) of heatmap commit data
export function generateSampleHeatmap(): HeatmapDay[] {
  const days: HeatmapDay[] = [];
  const today = new Date("2026-09-12");

  for (let i = 83; i >= 0; i--) {
    const d = new Date(today);
    d.setDate(d.getDate() - i);
    const dateStr = d.toISOString().split("T")[0];

    // Create realistic activity distribution
    const dayOfWeek = d.getDay();
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
    
    // Seed patterned activity
    const rand = Math.sin(i * 1.7) * 0.5 + 0.5;
    const apps = Math.floor(rand * (isWeekend ? 1 : 3));
    const dsa = Math.floor(rand * 8) + (isWeekend ? 4 : 2);
    const study = Math.floor(rand * 4) + (isWeekend ? 3 : 2);
    const interviews = (i === 4 || i === 8 || i === 15 || i === 22 || i === 35) ? 1 : 0;
    
    const count = apps + dsa + (interviews * 3) + study;

    days.push({
      date: dateStr,
      count,
      applications: apps,
      dsaQuestions: dsa,
      studyHours: study,
      interviews,
    });
  }

  return days;
}
